server:
  applicationContextPath: /app
  type: simple
  maxThreads: 1024
  connector:
    type: http
    port: 8085
  requestLog:
    appenders:
      - type: console
logging:
  level: INFO
  loggers:
    "org.glassfish.jersey.internal.Errors": ERROR
  appenders:
    - type: console
hosted:
    basePath: file:/tmp/jitstatic/remote
    servletName: jitstatic
    hostedEndpoint: git
    userName: huser
    secret: hseCr3t
    cors:
      allowedOrigins: "*"
